{% set name = "castepinput" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/castepinput-{{ version }}.tar.gz
  sha256: db4756a784cfc942ee57c0a04ef2270bcc12cb01187dfdd4ef5355882dbc6004

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - six

test:
  imports:
    - castepinput
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zhubonan/castepinput
  summary: A general reader/writer for CASTEP inputs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
